version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "ArjunSharda"
    labels:
      - "Dependabot"
      - "enhancement"
      - "Minor Priority"
